//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundrika.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int Id { get; set; }
        public string ItemID { get; set; }
        public string Entity { get; set; }
        public string Action { get; set; }
        public string Performedby { get; set; }
        public System.DateTime Created { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string IP { get; set; }
    }
}
