//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fundrika.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectCategory
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public long ProjectId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Project Project { get; set; }
    }
}
